# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-10.13'

steps:
- script: "clang example_c_language.c -o example_c_language"
  displayName: 'Compile the binary'
- script: "./example_c_language"
  displayName: 'Run the binary'